# Generated by Django 4.2.4 on 2023-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("completion_status", models.CharField(max_length=50)),
            ],
        ),
    ]
